### ISSUE TITLE
Installation instructions for Visual Studio for Code

### ISSUE THREAD

**Issue by ket000** [Jatz/PeopleSoftTools-vscode#1]
Please supply the installation instructions for this extension. I can not find it in Extension market place.

**Comment by Jatz** [comment]
Hi there, I wasn't actually ready to publish the extension to the marketplace as it is still in development. In any case, I've published it if you wanted to try it out.

**Comment by ket000** [comment]
Thanks. I was able to download and use it. It worked fine for my test
pcode.

**Comment by Jatz** [comment]
Good to hear.
