### ISSUE TITLE
Default Word Selection for PeopleCode in VSCode

### ISSUE THREAD

**Issue by ponns** [Jatz/PeopleSoftTools-vscode#2]
Thanks for this extension Jay. I just wanted to leave a small tip here.

Currently the default word selection does not include &. we often end up copying the variables without &. 

It can be modified by including the following settings. ( Settings > User or Workspace or Folder settings)
```JSON
"[peoplecode]": {
        "editor.wordSeparators": "`~!@#$%^*()-=+[{]}\\|;:'\",.<>/?",
    }
```

**Comment by Jatz** [comment]
Thanks for the tip @ponns. I was hoping to find a way to do this automatically for the extension, but it looks like this is currently not possible (see https://github.com/Microsoft/vscode/issues/33701). 

I've found a half-solution by adding the following entry to language-configuration.json:
```
"wordPattern":
{
    "pattern": "(-?\\d.\\d\\w)|([^`~!\\@#\\%\\^\\*\\(\\)-\\=+\\[\\{\\]\\}\\|\\;\\:\\'\\\"\\,\\.<>\\/\\?\\s]+)",
    "flags": "g"
}
```
This allows you to press ctrl-d on a particular variable name to select the variable with the &, but unfortunately, double-clicking on the variable still doesn't seem to work.

I'll add your tip to the readme for now.

**Comment by masebu** [comment]
Hi,

I applied @ponns tip but left % out of the wordseparators to allow full selection of system variables (ex. %Session), meta-sql (%CurrentDateIn) and so on. I don't see where that would be a problem.

regards

**Comment by Jatz** [comment]
Hi @masebu, thanks for that. I've modified the README accordingly to remove the %, since that seems to work well.
