### ISSUE TITLE
Remove leading fields in the trace file

### ISSUE THREAD

**Issue by iversond** [Jatz/PeopleSoftTools-vscode#3]
Often when viewing a trace file I remove the first columns to make the trace more readable. For example, with this trace line I would remove up to column 56: 

```sql
PSAPPSRV.16254 (27) 	 1-1633   13.50.41    0.000026 Cur#1.16254.FMS92UD RC=0 Dur=0.000015 COM Stmt=SELECT PORTAL_NAME, PORTAL_REFTYPE, PORTAL_OBJNAME FROM PSPRSMDEFN WHERE VERSION > :1 UNION SELECT PORTAL_NAME, PORTAL_REFTYPE, PORTAL_OBJNAME FROM PSPRSMDEL WHERE VERSION > :2
```

After 
```sql
Cur#1.16254.FMS92UD RC=0 Dur=0.000015 COM Stmt=SELECT PORTAL_NAME, PORTAL_REFTYPE, PORTAL_OBJNAME FROM PSPRSMDEFN WHERE VERSION > :1 UNION SELECT PORTAL_NAME, PORTAL_REFTYPE, PORTAL_OBJNAME FROM PSPRSMDEL WHERE VERSION > :2
```

Would it be possible to for the plugin to do that? Right now, I use column-select mode to remove those leaning columns by hand.

**Comment by Jatz** [comment]
Running the `PeopleSoft Tools - Tidy PeopleCode Trace` command  from the command palette should actually remove that information when the `peoplesoft-tools-tidy.removeHeaders` setting is `true`. Let me know whether that works for you.

**Comment by Jatz** [comment]
I've fixed an issue relating to the `PeopleSoft Tools - Tidy PeopleCode Trace` command that was not re-fetching the configuration settings every time the command was called. This has been added to version version 0.1.2

**Comment by iversond** [comment]
Yes, running the `Tidy PeopleCode Trace` command does remove those fields! Thanks!
