### ISSUE TITLE
Syntax Highlighting - rem comments

### ISSUE THREAD

**Issue by masebu** [Jatz/PeopleSoftTools-vscode#4]
Hi,

thanks for sharing this extension; I'm used to notepad++ but hear a lot of vsCode and your extension is definitely an incentive to change.

I do have a problem with it though:
Syntax Highlighting is incorrect regarding rem comments.
It considers rem as a single-line comment; actually they're block comments that begin with rem and end with semicolon.

Regards

**Comment by Jatz** [comment]
Hi there, thanks for logging this. I wasn't actually aware that rem comments were block comments. I've just committed a change to fix this. It should be available when version 0.1.3 gets published.

**Comment by masebu** [comment]
Thanks for the change :-)

**Comment by masebu** [comment]
Hi,
sorry to bother you again, but I have another problem: rem comments are detected whenever "rem" starts a word. They should activate only if rem is a whole word.

Application Designer:
![image](https://user-images.githubusercontent.com/19706602/41405406-ffd21568-6fc9-11e8-86ef-892541a30c71.png)

VS Code
![image](https://user-images.githubusercontent.com/19706602/41405453-12c00ff4-6fca-11e8-8a0a-393c82121755.png)

Can you do something about that ?

Thanks

**Comment by Jatz** [comment]
Thanks for letting me know. This should be fixed in 0.1.4.
