### ISSUE TITLE
Reference to `text.html.pcodedoc` in PeopleCode.tmLanguage

### ISSUE THREAD

**Issue by vfcp** [Jatz/PeopleSoftTools-vscode#6]
Hi!

https://github.com/Jatz/PeopleSoftTools-vscode/blob/acf0484f04aa21d3e84640d46ef3c372e3b349a9/syntaxes/PeopleCode.tmLanguage#L135 references an external scope `text.html.pcodedoc` which is not defined in the other grammars of this extension. Is this scope defined somewhere else? Should it be `text.html.basic`?

I found this minor issue in the tests of a syntax highlighter I'm working on, similar to github linguist. This doesn't cause any issue but since I've found it, I thought of sharing with you :)

Thanks a lot!

**Comment by Jatz** [comment]
Hi there,

Thanks for finding this. I have removed the reference.

Regards,

Jay
